name: Process YouTube Video

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'YouTube video URL'
        required: true
      video_id:
        description: 'Video ID'
        required: true

jobs:
  process_video:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv pip install yt-dlp opencv-python-headless

      - name: Run script to download video and save 100th frame
        env:
          VIDEO_URL: ${{ github.event.inputs.video_url }}
          VIDEO_ID: ${{ github.event.inputs.video_id }}
        run: python save_frame.py

      # fix this section

      - name: Pull latest changes
        run: git pull origin main

      - name: Add the saved frame
        run: git add .

      - name: Commit changes
        run: git commit -m "Add video frame ${{ github.event.inputs.video_id }}"

      - name: Push changes
        run: git push origin main

